version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app  # Monta o código dentro do container
      - /app/node_modules  # Evita sobrescrever os node_modules do container
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]  # Agora roda com nodemon

  frontend:
    build: ./meu-app
    ports:
      - "3000:3000"
    volumes:
      - ./meu-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
    restart: always

  flowise:
    image: flowiseai/flowise
    ports:
      - "3001:3000"
    volumes:
      - ./flowise_data:/root/.flowise
    environment:
      - PORT=3000
      - FLOWISE_USERNAME=admin
      - FLOWISE_PASSWORD=admin
    restart: always

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=nome_do_banco
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

