version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    command: ["node", "index.js"]

  frontend:
    build: ./meu-app
    ports:
      - "3000:3000"
    volumes:
      - ./meu-app:/app
    environment:
      - NODE_ENV=development
